services:
  mysql:
    image: mariadb:10.5
    container_name: zabbix-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_bin

  zabbix-server:
    image: zabbix/zabbix-server-mysql:${ZABBIX_VERSION}
    container_name: zabbix-server
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - zbx_alertscripts:/usr/lib/zabbix/alertscripts
      - zbx_modules:/usr/lib/zabbix/modules

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:${ZABBIX_VERSION}
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - mysql
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
      - PHP_TZ=America/Bogota

volumes:
  mysql_data:
  zbx_alertscripts:
  zbx_modules: